# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Main

concurrency:
  group: azure-CATCOLLAR
  cancel-in-progress: true

on:
  push:
    branches:
      - bugfix-*
      - enhancement-*
      - feature-*
      - workaround-*
      - dev
      - unstable
      - master

jobs:

  #=====================================================================================================================
  # Setup
  #=====================================================================================================================

  # Node 0
  setup-demikernel0:
    name: Node 0
    uses: demikernel/liburing-rs/.github/workflows/setup.yml@dev
    secrets:
      host: ${{ secrets.CATCOLLAR_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Node 1
  setup-demikernel1:
    name: Node 1
    uses: demikernel/liburing-rs/.github/workflows/setup.yml@dev
    secrets:
      host: ${{ secrets.CATCOLLAR_HOSTNAME_B }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #=====================================================================================================================
  # Setup Completed
  #=====================================================================================================================

  setup:
    name: Setup Completed
    needs: [setup-demikernel0, setup-demikernel1]
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Setup Completed!"

  #=====================================================================================================================
  # Build
  #=====================================================================================================================

  # Node 0
  build-demikernel0:
    name: Node 0
    needs: [setup]
    uses: demikernel/liburing-rs/.github/workflows/build.yml@dev
    secrets:
      host: ${{ secrets.CATCOLLAR_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Node 1
  build-demikernel1:
    name: Node 1
    needs: [setup]
    uses: demikernel/liburing-rs/.github/workflows/build.yml@dev
    secrets:
      host: ${{ secrets.CATCOLLAR_HOSTNAME_B }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #=====================================================================================================================
  # Build Completed
  #=====================================================================================================================

  # Node 0
  build:
    name: Build Completed
    needs: [build-demikernel0, build-demikernel1]
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Build Completed!"

  #=====================================================================================================================
  # Test
  #=====================================================================================================================

  # Node 0
  test-demikernel0:
    name: Node 0
    needs: [build]
    uses: demikernel/liburing-rs/.github/workflows/test.yml@dev
    secrets:
      host: ${{ secrets.CATCOLLAR_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Node 1
  test-demikernel1:
    name: Node 1
    needs: [build]
    uses: demikernel/liburing-rs/.github/workflows/test.yml@dev
    secrets:
      host: ${{ secrets.CATCOLLAR_HOSTNAME_B }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #=====================================================================================================================
  # Test Completed
  #=====================================================================================================================

  # Node 0
  test:
    name: Test Completed
    needs: [test-demikernel0, test-demikernel1]
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Test Completed!"

  #=====================================================================================================================
  # Cleanup
  #=====================================================================================================================

  # Node 0
  cleanup-demikernel0:
    name: Node 0
    if: always()
    needs: [test]
    uses: demikernel/liburing-rs/.github/workflows/cleanup.yml@dev
    secrets:
      host: ${{ secrets.CATCOLLAR_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Node 1
  cleanup-demikernel1:
    name: Node 1
    if: always()
    needs: [test]
    uses: demikernel/liburing-rs/.github/workflows/cleanup.yml@dev
    secrets:
      host: ${{ secrets.CATCOLLAR_HOSTNAME_B }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}
